### ISSUE TITLE
Too much popups in the keyboard

### ISSUE THREAD

**Issue by Ahmad-Shah-GEB** [AdroitAdorKhan/RidmikBoard#10]
" or ' are used a lot. But when I try to use that, six options come out, which is disconcerting. There should be fewer option in the front board. Such many options, which are less oftenly used, should be in the alternative or numerical tabs of the keyboard, not on the front tab.

**Comment by AdroitAdorKhan** [comment]
Ain't this better to get all the quick symbols at one place?! I thought it will help to write using those symbols, without going to symbol layout! Anyway, I will reduce few symbols!

**Comment by x9kill** [comment]
Its better to have more symbols at one place! Saves time!
' or " issue ain't that much important compared to more symbols!

**Comment by AdroitAdorKhan** [comment]
@Ahmad-Shah-GEB Use the latest release, and if you find this issue bugging u anymore, then re-open the issue! :)
