### ISSUE TITLE
র‍্য button is missing

### ISSUE THREAD

**Issue by Ahmad-Shah-GEB** [AdroitAdorKhan/RidmikBoard#11]
In ridmik, র‍্য writing is a problem, as it becomes র্য. So the developers added র‍্য button as another letter. Your app is missing that important feature. Please add that.

**Comment by AdroitAdorKhan** [comment]
র‍্য is available in Probhat layout. But, I will bring back it in symbols layout in next update!

**Comment by AdroitAdorKhan** [comment]
র‍্য were added back in latest beta, so will be in latest STABLE release! :) So I'm closing this issue!
