### ISSUE TITLE
Missing curly brackets

### ISSUE THREAD

**Issue by sohagmahin** [AdroitAdorKhan/RidmikBoard#12]
Curly brackets **"{ }"** are not present in the ridmik board v1.10.1. Please add this.

**Comment by AdroitAdorKhan** [comment]
@sohagmahin Kindly check on () (Round Brackets) Pop-Ups! :)

**Comment by AdroitAdorKhan** [comment]
I'm closing the thread, and make sure u r using the latest one! :)

**Comment by sohagmahin** [comment]
Thanks,  I am using the latest version. Good Job. Keep it up.
