### ISSUE TITLE
Theme Request

### ISSUE THREAD

**Issue by AdroitAdorKhan** [AdroitAdorKhan/RidmikBoard#3]
Few of our users have requested to change base themes. I might change few of them. 

Requests -
- [ ] Ridmik Mint Enter Button. 
- [ ] Photo Background.
- [ ] Pink/Yellow Theme.
- [x] IOS Theme.
- [ ] More Themes. (x)

So these have been added to our to-do list!

Else, if you need anything other, contact me on fb or telegram!

**Comment by n4y33m** [comment]
Photo background would be better so that user can add images to their choice to make the same keyboard in the different design. Like, I love minimalistic, so if I add a minimal background, it will be pretty minimal. :)

**Comment by AdroitAdorKhan** [comment]
@n4y33m I'm working on 3.1.8 Ridmik base now! There are few things to fix and implement! Once, everything becomes stable, I would start working on theme requests! :)

**Comment by uddin110** [comment]
Great work sir, 
Plz add more Theme.
Thanks once again 😊

**Comment by kuntalkundu** [comment]
I love the black Amoled theme. It's really eye catching!

**Comment by minhaj14d** [comment]
When we'll get the ridmik board plus? 😁

**Comment by AdroitAdorKhan** [comment]
**Project CLOSED!**
