### ISSUE TITLE
প্রভাত লেআউট দিয়ে "র‌্যাম " কিভাবে লিখব?

### ISSUE THREAD

**Issue by ashickurnoor** [AdroitAdorKhan/RidmikBoard#6]
প্রভাত লেআউট দিয়ে "র‌্যাম " কিভাবে লিখব?

**Comment by uddin110** [comment]
"য়" long press করুন,তাহলে "র‍্য" দেখতে পাবেন, +া + ম

**Comment by ashickurnoor** [comment]
"র্য" হয়ে যায়। "র‍্য" লেখার জন্য escape sequence ব্যবহার করা লাগে। যেটা এখানে নাই

**Comment by AdroitAdorKhan** [comment]
র‍্যাম = য় (লং প্রেস করে 'র‍্য' সেলেক্ট করুন) + া + ম

**Comment by ashickurnoor** [comment]
জাযাকাল্লাহ খায়ের

**Comment by AdroitAdorKhan** [comment]
:)

**Comment by ablonewolf** [comment]
কম্পিউটারে কিভাবে লিখব? প্রভাত সিস্টেমে ইনস্টল করা।।

**Comment by dreygur** [comment]
র‌্যাম

**Comment by dreygur** [comment]
> কম্পিউটারে কিভাবে লিখব? প্রভাত সিস্টেমে ইনস্টল করা।।

`r\/Zm` => `র‌্যাম`
