### ISSUE TITLE
Google Voice Speech to Text Not working

### ISSUE THREAD

**Issue by swarupsro** [AdroitAdorKhan/RidmikBoard#7]
Tested on Messenger!

**Comment by AdroitAdorKhan** [comment]
@swarupsro did u check permission? to make 'Voice Recognition' work, you have to give permission to the app. Check again, and report! :)

**Comment by swarupsro** [comment]
Sorry ! it was my fault ! Ok Works 👍

**Comment by AdroitAdorKhan** [comment]
@swarupsro it's alright! :) You can always check about any issue on our web! :) or, ask here or XDA! :D
