### ISSUE TITLE
request to add ZWNJ

### ISSUE THREAD

**Issue by kuntalkundu** [AdroitAdorKhan/RidmikBoard#8]
in original Probhat or any fixed keyboard layout (desktop version) there is a key called ZWNJ and ZWJ which is used between two letters to keep separate them after using "Hasant" to form a new Jukta Barna. In Ridmik, when hasant (joiner key) used in middle of two letter, it creates a JuktoBarna. If anybody wish to keep them seperated after using hasant there are no way to do that. A Zero with Non Joiner (ZWNJ) key can solve this problem. Could it be added in next update? it's symbol is `

**Comment by AdroitAdorKhan** [comment]
So the thing is, all I have to do is add this (`) symbol?

**Comment by kuntalkundu** [comment]
এই কী টা অলরেডি রিদমিকে আছেই, alt ভিউ এ পাওয়া যাবে। তবে এটার মজা হল, এটা প্রেস করলে ওই সিম্বলটা ডিসপ্লে হয় না,  কিন্তু তারপর টাইপ করা কোন বর্ণ আগের বর্ণের সাথে যুক্ত হবে না হসন্ত দিলেও। ডেস্কটপে এমনটাই হয়। সেটাই রিদমিকে চালু করতে হবে।

**Comment by AdroitAdorKhan** [comment]
Closing the issue, as 'ZWNJ' & ;'ZWJ' were added in latest release. :)

**Comment by kuntalkundu** [comment]
Sure please close it down. Problem is solved! Thanks a ton!! 👍👍

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
