### ISSUE TITLE
Issues with @

### ISSUE THREAD

**Issue by Ahmad-Shah-GEB** [AdroitAdorKhan/RidmikBoard#9]
The ”a” sign is used a lot. but while I try to use that, sometimes Å sign is written instead of @. I think @ can be removed from this button to elsewhere. Thanks.

**Comment by Ahmad-Shah-GEB** [comment]
Sorry, I suggest that Å should be removed ‘A’ button. only @ should be there.

**Comment by AdroitAdorKhan** [comment]
Å, this is Angstrom, few Science Students and Teachers suggested me to add few Science related symbols! This is one of them! You can simply use @ instead of Å! Thanks!

**Comment by AdroitAdorKhan** [comment]
This issue was fixed, in latest beta build! :)
